// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxgf4VTiFc_YvVqqgr6vS9c3ByRO-UVk',
    appId: '1:33946982957:web:18eaa78f18cb1dbee0b6a4',
    messagingSenderId: '33946982957',
    projectId: 'tazk-d9069',
    authDomain: 'tazk-d9069.firebaseapp.com',
    storageBucket: 'tazk-d9069.firebasestorage.app',
    measurementId: 'G-46Y7B2E3P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFuxBURRz7Z7Dz4nGplFJCcGWtH8iCbA',
    appId: '1:33946982957:android:71a3cd2588b8950fe0b6a4',
    messagingSenderId: '33946982957',
    projectId: 'tazk-d9069',
    storageBucket: 'tazk-d9069.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBE-_y0GE0oRdjSo9xzeDpYJy5qFqyypQ',
    appId: '1:33946982957:ios:4c8d753a19abdf83e0b6a4',
    messagingSenderId: '33946982957',
    projectId: 'tazk-d9069',
    storageBucket: 'tazk-d9069.firebasestorage.app',
    iosBundleId: 'com.tazkarti.alert.tazkartiAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBE-_y0GE0oRdjSo9xzeDpYJy5qFqyypQ',
    appId: '1:33946982957:ios:4c8d753a19abdf83e0b6a4',
    messagingSenderId: '33946982957',
    projectId: 'tazk-d9069',
    storageBucket: 'tazk-d9069.firebasestorage.app',
    iosBundleId: 'com.tazkarti.alert.tazkartiAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbxgf4VTiFc_YvVqqgr6vS9c3ByRO-UVk',
    appId: '1:33946982957:web:c2ec5e312c397b05e0b6a4',
    messagingSenderId: '33946982957',
    projectId: 'tazk-d9069',
    authDomain: 'tazk-d9069.firebaseapp.com',
    storageBucket: 'tazk-d9069.firebasestorage.app',
    measurementId: 'G-YT746DX2HN',
  );
}
